# Machine Learning at the Extreme Edge
site_name: ML@E2dge

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: black
  font:
    text:Ubuntu Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

plugins:
    - search

edit_uri: ""

nav:
  - Home: 'index.md'
  - Case Study: 'case study.md'
  - Embedded Machine Learning Workflow: 'workflow.md'
  - Supervisory Group: 'supervisory_group.md'

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://be.linkedin.com/in/joeriverbiest

repo_url: https://github.com/MLatE2dge