site_name: ML@E2dge

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: black
  font:
    text:Ubuntu Mono

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
    - search

edit_uri: ""

nav:
  - Home: 'index.md'
  - Test: 'test.md'
